name: 01_4years_1day_supabase

on:
  schedule:
    # UTC 00:10 -> 한국 시간(KST) 09:10
    - cron: '*/5 0 * * *'
  workflow_dispatch: # 테스트를 위해 수동 실행 버튼 활성화

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # 사용할 파이썬 버전

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # 필요한 라이브러리가 있다면 여기에 직접 입력 가능 (예: pip install pandas)

      - name: Run script
        run: python 01_BTC4year\backend\src\fourYear\01_4years_1day_supabase.py # 실제 실행할 파이썬 파일명으로 바꾸세요!